# Generated by Django 5.2.6 on 2025-09-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
