# Generated by Django 5.2.6 on 2025-09-14 10:28

import django.core.validators
import django.db.models.deletion
import sibijaks25.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(help_text='Nama lengkap sesuai KTP atau identitas resmi lainnya.', max_length=500)),
                ('institusi', models.CharField(help_text='Institusi harus berbeda dengan ketua tim / penulis utama.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(help_text='Nama lengkap sesuai KTP atau identitas resmi lainnya.', max_length=255)),
                ('email', models.EmailField(help_text='Email nantinya akan digunakan untuk login ke situs web ini.', max_length=254, unique=True)),
                ('nomor_wa', models.CharField(help_text='Nomor WA nantinya akan digunakan untuk login ke situs web ini.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Nomor WA minimal 5 karakter.')], verbose_name='Nomor WA')),
                ('institusi', models.CharField(max_length=500)),
                ('pekerjaan', models.CharField(help_text='Jika Anda mahasiswa, isikan "Mahasiswa"', max_length=255, verbose_name='Profesi/Pekerjaan/Jabatan')),
                ('pendidikan', models.CharField(choices=[('d3', 'D3'), ('s1', 'D4 / S1'), ('s2', 'S2'), ('s3', 'S3')], max_length=5, verbose_name='Pendidikan Terakhir')),
                ('pasfoto', models.ImageField(blank=True, help_text='Upload pasfoto formal dengan latar belakang merah, rasio 2x3, ukuran maksimal 2MB.', max_length=500, null=True, upload_to='pasfoto/', validators=[sibijaks25.models.validate_pasfoto])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naskah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=500)),
                ('abstrak', models.TextField()),
                ('naskah', models.FileField(blank=True, help_text='Unggah naskah dalam format PDF, ukuran maksimal 20 MB.', max_length=500, null=True, upload_to='naskah/')),
                ('verified', models.BooleanField(default=False)),
                ('kolaborators', models.ManyToManyField(to='sibijaks25.kolaborator')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibijaks25.peserta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kolaborator',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kolaborators', to='sibijaks25.peserta'),
        ),
    ]
