# Generated by Django 5.2.6 on 2025-09-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0002_kolaborator_peserta_naskah_kolaborator_peserta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naskah',
            name='abstrak',
            field=models.TextField(help_text='Maksimal 250 kata.', verbose_name='Concept Proposal (Abstrak)'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='kolaborators',
            field=models.ManyToManyField(help_text='Minimal satu harus dipilih.', to='sibijaks25.kolaborator', verbose_name='Kolaborator'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naskahs', to='sibijaks25.peserta'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nomor_wa',
            field=models.CharField(help_text='Nomor WA nantinya akan digunakan untuk login ke situs web ini.', max_length=20, unique=True, verbose_name='Nomor WA'),
        ),
    ]
