# Generated by Django 5.2.6 on 2025-09-14 15:01

import sibijaks25.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0003_alter_naskah_abstrak_alter_naskah_kolaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naskah',
            name='jenis_naskah',
            field=models.CharField(choices=[('art', 'Artikel Ilmiah'), ('pb', 'Policy Brief')], default='art', max_length=5, verbose_name='Jenis Naskah'),
        ),
        migrations.AddField(
            model_name='peserta',
            name='is_mahasiswa',
            field=models.BooleanField(default=False, verbose_name='Saya ingin mendaftar kompetisi ini sebagai mahasiswa'),
        ),
        migrations.AddField(
            model_name='peserta',
            name='mahasiswa',
            field=models.CharField(blank=True, choices=[('d3', 'D3'), ('s1', 'D4 / S1'), ('s2', 'S2 / pasca sarjana'), ('s3', 'S3 / post doktoral')], max_length=3, null=True, verbose_name='Mahasiswa jenjang'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='institusi',
            field=models.CharField(help_text='Jika Anda mendaftar sebagai mahasiswa, tuliskan nama perguruan tinggi.', max_length=500),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pasfoto',
            field=models.ImageField(blank=True, help_text='Upload pasfoto formal dengan latar belakang merah, rasio 2x3, ukuran maksimal 2 MB.', max_length=500, null=True, upload_to='pasfoto/', validators=[sibijaks25.models.validate_pasfoto]),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesi/Pekerjaan/Jabatan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('d3', 'D3'), ('s1', 'D4 / S1'), ('s2', 'S2'), ('s3', 'S3')], help_text='Kosongkan jika tidak relevan', max_length=5, null=True, verbose_name='Pendidikan Terakhir'),
        ),
    ]
