# Generated by Django 5.2.6 on 2025-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0004_naskah_jenis_naskah_peserta_is_mahasiswa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kolaborator',
            name='email',
            field=models.EmailField(default='mail@mail.com', help_text='Email nantinya akan digunakan untuk login ke situs web ini.', max_length=254),
        ),
        migrations.AddField(
            model_name='kolaborator',
            name='nomor_wa',
            field=models.CharField(default='0', help_text='Nomor WA nantinya akan digunakan untuk login ke situs web ini.', max_length=20, verbose_name='Nomor WA'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='abstrak',
            field=models.TextField(help_text='Maksimal abstrak 400 kata (Policy Brief), atau 2 halaman A4 ukuran font 11 (Artikel Ilmiah).', verbose_name='Concept Proposal (Abstrak)'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='kolaborators',
            field=models.ManyToManyField(help_text='Minimal satu orang harus dipilih.', to='sibijaks25.kolaborator', verbose_name='Kolaborator'),
        ),
    ]
