# Generated by Django 5.2.6 on 2025-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0005_kolaborator_email_kolaborator_nomor_wa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolaborator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kolaborator',
            name='nomor_wa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WA'),
        ),
    ]
