# Generated by Django 5.2.6 on 2025-09-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0006_alter_kolaborator_email_alter_kolaborator_nomor_wa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolaborator',
            name='institusi',
            field=models.CharField(help_text='Minimal satu kolaborator harus berasal dari institusi yang berbeda dengan ketua tim atau penulis utama.', max_length=500),
        ),
    ]
