# Generated by Django 5.2.6 on 2025-09-15 00:30

import sibijaks25.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0007_alter_kolaborator_institusi'),
    ]

    operations = [
        migrations.AddField(
            model_name='naskah',
            name='file_abstrak',
            field=models.FileField(blank=True, help_text='Unggah file abstrak dalam format PDF, ukuran maksimal 5 MB.', max_length=500, null=True, upload_to='abstrak/', validators=[sibijaks25.models.validate_abstrak_pdf]),
        ),
    ]
