# Generated by Django 5.2.6 on 2025-09-15 05:58

import sibijaks25.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0008_naskah_file_abstrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='kolaborator',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kolaborator',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('d3', 'D3'), ('s1', 'D4 / S1'), ('s2', 'S2'), ('s3', 'S3')], help_text='Kosongkan jika tidak relevan', max_length=5, null=True, verbose_name='Pendidikan Terakhir'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='abstrak',
            field=models.TextField(help_text='Maksimal konsep 400 kata (Policy Brief), 1150 kata (Artikel Ilmiah).', verbose_name='Konsep'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='file_abstrak',
            field=models.FileField(blank=True, help_text='Unggah file konsep dalam format PDF, ukuran maksimal 5 MB.', max_length=500, null=True, upload_to=sibijaks25.models.konsep_dir_path, validators=[sibijaks25.models.validate_abstrak_pdf], verbose_name='File Konsep'),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='naskah',
            field=models.FileField(blank=True, help_text='Unggah naskah dalam format PDF, ukuran maksimal 20 MB.', max_length=500, null=True, upload_to=sibijaks25.models.naskah_dir_path),
        ),
    ]
