# Generated by Django 5.2.6 on 2025-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0009_kolaborator_pekerjaan_kolaborator_pendidikan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomor_wa', models.CharField(max_length=20, unique=True, verbose_name='Nomor WA')),
                ('institusi', models.CharField(blank=True, max_length=500, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Juri',
            },
        ),
        migrations.AlterModelOptions(
            name='naskah',
            options={'verbose_name_plural': 'Naskah'},
        ),
        migrations.AlterModelOptions(
            name='peserta',
            options={'verbose_name_plural': 'Peserta'},
        ),
        migrations.AlterField(
            model_name='kolaborator',
            name='pekerjaan',
            field=models.CharField(blank=True, help_text='Jika mahasiswa, tuliskan "Mahasiswa"', max_length=255, null=True),
        ),
    ]
