# Generated by Django 5.2.6 on 2025-09-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0010_juri_alter_naskah_options_alter_peserta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juri',
            name='is_panitia',
            field=models.BooleanField(default=False),
        ),
    ]
