# Generated by Django 5.2.6 on 2025-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0011_juri_is_panitia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=255)),
                ('kode', models.TextField(help_text='Kode HTML/JS untuk countdown timer.')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
