# Generated by Django 5.2.6 on 2025-09-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0012_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='juri',
            name='is_supersubstansi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juri',
            name='tahap',
            field=models.IntegerField(choices=[(1, 'Tahap 1'), (2, 'Tahap 2'), (3, 'Tahap 3')], default=1),
        ),
        migrations.AddField(
            model_name='naskah',
            name='status_naskah',
            field=models.IntegerField(choices=[(100, 'Terunggah'), (200, 'Lolos Admin 1'), (300, 'Lolos Admin 2'), (666, 'Gugur')], default=100, verbose_name='Status Naskah'),
        ),
        migrations.AddField(
            model_name='naskah',
            name='verifier1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='naskah',
            name='verifier2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Review1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('s1', models.BooleanField()),
                ('s2', models.BooleanField()),
                ('s3', models.BooleanField()),
                ('s4', models.BooleanField()),
                ('juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews1', to='sibijaks25.juri')),
                ('naskah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews1', to='sibijaks25.naskah')),
            ],
            options={
                'verbose_name': 'Review 1',
                'verbose_name_plural': 'Review 1',
                'unique_together': {('juri', 'naskah')},
            },
        ),
    ]
