# Generated by Django 5.2.6 on 2025-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0013_juri_is_supersubstansi_juri_tahap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review1',
            name='s5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review1',
            name='s6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review1',
            name='s1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review1',
            name='s2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review1',
            name='s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review1',
            name='s4',
            field=models.BooleanField(default=False),
        ),
    ]
