# Generated by Django 5.2.6 on 2025-09-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0014_review1_s5_review1_s6_alter_review1_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review1',
            name='komentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
