# Generated by Django 5.2.6 on 2025-09-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0015_review1_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='naskah',
            name='komentar1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naskah',
            name='komentar2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naskah',
            name='s1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='naskah',
            name='s2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='naskah',
            name='s3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='naskah',
            name='s4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='naskah',
            name='s5',
            field=models.BooleanField(default=False),
        ),
    ]
