# Generated by Django 5.2.6 on 2025-09-30 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0016_naskah_komentar1_naskah_komentar2_naskah_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juri',
            name='jenis_naskah',
            field=models.CharField(choices=[('art', 'AI'), ('pb', 'PB'), ('artpb', 'AI/PB')], default='artpb', help_text='Jenis naskah yang diberikan untuk di-review oleh juri ini.', max_length=10),
        ),
        migrations.CreateModel(
            name='Review2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('s1', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('s5', models.IntegerField(default=0)),
                ('s6', models.IntegerField(default=0)),
                ('komentar', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews2', to='sibijaks25.juri')),
                ('naskah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews2', to='sibijaks25.naskah')),
            ],
            options={
                'verbose_name': 'Review 2',
                'verbose_name_plural': 'Review 2',
                'unique_together': {('juri', 'naskah')},
            },
        ),
        migrations.AddField(
            model_name='naskah',
            name='juris',
            field=models.ManyToManyField(blank=True, related_name='naskahs', through='sibijaks25.Review2', to='sibijaks25.juri', verbose_name='Juri Tahap 2'),
        ),
    ]
