# Generated by Django 5.2.6 on 2025-10-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0017_juri_jenis_naskah_review2_naskah_juris'),
    ]

    operations = [
        migrations.AddField(
            model_name='review2',
            name='lanjut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='juris',
            field=models.ManyToManyField(blank=True, related_name='naskahs', through='sibijaks25.Review2', to='sibijaks25.juri', verbose_name='Reviewer'),
        ),
    ]
