# Generated by Django 5.2.6 on 2025-10-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0018_review2_lanjut_alter_naskah_juris'),
    ]

    operations = [
        migrations.AddField(
            model_name='review2',
            name='s10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review2',
            name='s7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review2',
            name='s8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review2',
            name='s9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review2',
            name='total2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='naskah',
            name='status_naskah',
            field=models.IntegerField(choices=[(100, 'Terunggah'), (200, 'Lolos Konsep'), (300, 'Lolos Admin 2'), (666, 'Gugur')], default=100, verbose_name='Status Naskah'),
        ),
    ]
