# Generated by Django 5.2.6 on 2025-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0019_review2_s10_review2_s7_review2_s8_review2_s9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review2',
            name='komentar2',
            field=models.TextField(blank=True),
        ),
    ]
