# Generated by Django 5.2.6 on 2025-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0020_review2_komentar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='naskah',
            name='meminta_data',
            field=models.BooleanField(default=False),
        ),
    ]
