# Generated by Django 5.2.6 on 2025-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0021_naskah_meminta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='naskah',
            name='terlambat',
            field=models.BooleanField(default=False),
        ),
    ]
