# Generated by Django 5.2.6 on 2025-12-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibijaks25', '0022_naskah_terlambat'),
    ]

    operations = [
        migrations.AddField(
            model_name='review2',
            name='komentar3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review2',
            name='total3',
            field=models.IntegerField(default=0),
        ),
    ]
